-- Full legacy ambulance request setup
-- Use this if public.ambulance_requests is missing or incomplete.
-- Paste into the Supabase SQL Editor and run once.

begin;

create table if not exists public.ambulance_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  hospital_name text not null,
  phone text null,
  status text not null default 'pending',
  patient_name text null,
  pickup_location text null,
  emergency_note text null,
  estimated_time text null,
  response_note text null,
  reviewed_at timestamp with time zone null,
  verified_patient boolean not null default false,
  latitude double precision null,
  longitude double precision null,
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

alter table public.ambulance_requests
add column if not exists patient_name text null,
add column if not exists pickup_location text null,
add column if not exists emergency_note text null,
add column if not exists estimated_time text null,
add column if not exists response_note text null,
add column if not exists reviewed_at timestamp with time zone null,
add column if not exists verified_patient boolean not null default false,
add column if not exists latitude double precision null,
add column if not exists longitude double precision null,
add column if not exists created_at timestamp with time zone not null default timezone('utc', now()),
add column if not exists updated_at timestamp with time zone not null default timezone('utc', now());

create index if not exists idx_ambulance_requests_user_id
on public.ambulance_requests (user_id);

create index if not exists idx_ambulance_requests_hospital_name
on public.ambulance_requests (hospital_name);

create index if not exists idx_ambulance_requests_status
on public.ambulance_requests (status);

create or replace function public.set_ambulance_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_ambulance_requests_updated_at
on public.ambulance_requests;

create trigger trg_ambulance_requests_updated_at
before update on public.ambulance_requests
for each row
execute function public.set_ambulance_requests_updated_at();

alter table public.ambulance_requests enable row level security;

drop policy if exists "Patients can insert their own ambulance requests" on public.ambulance_requests;
create policy "Patients can insert their own ambulance requests"
on public.ambulance_requests
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Patients can view their own ambulance requests" on public.ambulance_requests;
create policy "Patients can view their own ambulance requests"
on public.ambulance_requests
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Hospital dashboard can read ambulance requests" on public.ambulance_requests;
create policy "Hospital dashboard can read ambulance requests"
on public.ambulance_requests
for select
to anon, authenticated
using (true);

drop policy if exists "Hospital dashboard can update ambulance requests" on public.ambulance_requests;
create policy "Hospital dashboard can update ambulance requests"
on public.ambulance_requests
for update
to anon, authenticated
using (true)
with check (true);

commit;
