-- Fresh City Hospital ambulance request table
-- Paste this into the Supabase SQL Editor and run it once.

begin;

create table if not exists public.city_hospital_ambulance_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  hospital_name text not null default 'City Hospital',
  patient_name text null,
  phone text null,
  pickup_location text null,
  emergency_note text null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  estimated_time text null,
  response_note text null,
  verified_patient boolean not null default false,
  latitude double precision null,
  longitude double precision null,
  reviewed_at timestamp with time zone null,
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

create index if not exists idx_city_hospital_ambulance_requests_user_id
on public.city_hospital_ambulance_requests (user_id);

create index if not exists idx_city_hospital_ambulance_requests_status
on public.city_hospital_ambulance_requests (status);

create index if not exists idx_city_hospital_ambulance_requests_created_at
on public.city_hospital_ambulance_requests (created_at desc);

create or replace function public.set_city_hospital_ambulance_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_city_hospital_ambulance_requests_updated_at
on public.city_hospital_ambulance_requests;

create trigger trg_city_hospital_ambulance_requests_updated_at
before update on public.city_hospital_ambulance_requests
for each row
execute function public.set_city_hospital_ambulance_requests_updated_at();

alter table public.city_hospital_ambulance_requests enable row level security;

drop policy if exists "Patients can insert their own City Hospital ambulance requests" on public.city_hospital_ambulance_requests;
create policy "Patients can insert their own City Hospital ambulance requests"
on public.city_hospital_ambulance_requests
for insert
to authenticated
with check (
  auth.uid() = user_id
  and hospital_name = 'City Hospital'
);

drop policy if exists "Patients can view their own City Hospital ambulance requests" on public.city_hospital_ambulance_requests;
create policy "Patients can view their own City Hospital ambulance requests"
on public.city_hospital_ambulance_requests
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Hospital dashboard can read City Hospital ambulance requests" on public.city_hospital_ambulance_requests;
create policy "Hospital dashboard can read City Hospital ambulance requests"
on public.city_hospital_ambulance_requests
for select
to anon, authenticated
using (hospital_name = 'City Hospital');

drop policy if exists "Hospital dashboard can update City Hospital ambulance requests" on public.city_hospital_ambulance_requests;
create policy "Hospital dashboard can update City Hospital ambulance requests"
on public.city_hospital_ambulance_requests
for update
to anon, authenticated
using (hospital_name = 'City Hospital')
with check (hospital_name = 'City Hospital');

commit;
